name: iso_languages
description: "A Flutter package to work with ISO 639-1 language codes, providing language names, native names, and utility functions."
version: 1.0.1
homepage: https://github.com/devtanvirmahtab/iso_languages

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# License information
license: MIT
